GET http://localhost:3000/todos/?status=TO%20DO
###

get http://localhost:3000/todos/?priority=HIGH
###

get http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###

get http://localhost:3000/todos/?search_q=Play
###

get http://localhost:3000/todos/:todo_Id/
###


POST http://localhost:3000/todos/
Content-Type: application/json
{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
};